### PR TITLE
fix: only print failed preconditions

### LINKED ISSUE #396: preconditions: only print failed preconditions
> We probably don't need to print the preconditions if they passed

_Originally posted by @benmccann in https://github.com/svelte-add/svelte-add/issues/379#issuecomment-2166905263_
            

Context:
Currently we print all preconditions (failed and passed). Similar to the recently implement post-conditions, we should only print failed preconditions, and only print the appropriate message, if at least one precondition failed.

### PR DESCRIPTION
**Pull request by manuel3108**
Closes #396

### CODE REVIEW

File: packages/core/adder/preconditions.ts [hunk 1]
```diff
@@ -86,32 +86,34 @@ export async function validatePreconditions<Args extends OptionDefinition>(
...
 
-        if (!allPreconditionsPassed && isTesting) {
-            throw new Error(`Preconditions failed: ${preconditionLog.join(" / ")}`);
-        }
-        if (isTesting) return;
+    if (allPreconditionsPassed) {
+        return;
+    } else if (!allPreconditionsPassed && isTesting) {
+        throw new Error(`Preconditions failed: ${preconditionLog.join(" / ")}`);
+    }
```
Comment (AdrianGonz97) [inline packages/core/adder/preconditions.ts:106]: since we're returning early when they all pass, we don't really need to check if it's still `false`
```suggestion
    if (allPreconditionsPassed) {
        return;
    } 
    
    if (isTesting) {
        throw new Error(`Preconditions failed: ${preconditionLog.join(" / ")}`);
    }
```

File: packages/core/adder/preconditions.ts [hunk 2]
```diff
@@ -86,32 +86,34 @@ export async function validatePreconditions<Args extends OptionDefinition>(
...
+
+    let allMessages = "";
+    for (const [i, message] of preconditionLog.entries()) {
+        allMessages += `- ${message}${i == preconditionLog.length - 1 ? "" : "\n"}`;
+    }
```
Comment (AdrianGonz97) [inline packages/core/adder/preconditions.ts:111]: I find this to be a bit easier to parse, though it may just be a preference:
```suggestion
    const allMessages = preconditionLog.map((msg) => `- ${msg}`).join("\n");
```

File: packages/core/adder/preconditions.ts [hunk 3]
```diff
@@ -86,32 +86,34 @@ export async function validatePreconditions<Args extends OptionDefinition>(
...
 
-        messagePrompt("Preconditions:", allMessages);
+    messagePrompt("Preconditions not met", allMessages);
 
-        if (!allPreconditionsPassed) {
-            await askUserToContinueWithFailedPreconditions();
-        }
+    if (!allPreconditionsPassed) {
+        await askUserToContinueWithFailedPreconditions();
     }
```
Comment (AdrianGonz97) [inline packages/core/adder/preconditions.ts:117]: same as the first comment - since we're returning early if they all pass, we can safely remove this condition
```suggestion
    await askUserToContinueWithFailedPreconditions();
```

**Review by AdrianGonz97 — CHANGES_REQUESTED** [review]
looks good! just some have some minor nits:

File: packages/core/adder/preconditions.ts (hunk 2 above)
Comment (manuel3108) [reply packages/core/adder/preconditions.ts]: Don't know what my brain was thinking there, you are 150% right!
