### PR TITLE
fix: validate cli adder names

### LINKED ISSUE #460: specifying adders from CLI is broken
### Topic

cli

### Version

2.3.2

### Expected behavior

this should work:
```
npx svelte-add@latest tailwind
```

### Actual behavior

didn't do anything

### PR DESCRIPTION
**Pull request by manuel3108**
Closes #460

### CODE REVIEW

File: packages/core/adder/options.ts [hunk 1]
```diff
@@ -137,12 +137,27 @@ export function prepareAndParseCliOptions<Args extends OptionDefinition>(adderDe
...
     return options;
 }
 
+function validateAddersOrExit<Args extends OptionDefinition>(adderDetails: AdderDetails<Args>[], selectedAdderIds: string[]) {
+    const validAdderIds = adderDetails.map((x) => x.config.metadata.id);
+    const invalidAdders = selectedAdderIds.filter((x) => !validAdderIds.includes(x));
+
+    if (invalidAdders.length > 0) {
+        console.log("Invalid adder(s) selected:", invalidAdders.join(", "));
+        process.exit(0);
```
Comment (AdrianGonz97) [inline packages/core/adder/options.ts:155]:
```suggestion
        console.error("Invalid adder(s) selected:", invalidAdders.join(", "));
        process.exit(1);
```

File: packages/core/adder/options.ts [hunk 2]
```diff
@@ -137,12 +137,27 @@ export function prepareAndParseCliOptions<Args extends OptionDefinition>(adderDe
     const options = program.opts();
 
     if (multipleAdders) {
-        options.adder = program.args;
+        const selectedAdderIds: string[] = program.args ?? [];
```
Comment (AdrianGonz97) [inline packages/core/adder/options.ts:140]: this should be inferable
```suggestion
        const selectedAdderIds = program.args ?? [];
```

File: packages/core/adder/options.ts [hunk 3]
```diff
@@ -137,12 +137,27 @@ export function prepareAndParseCliOptions<Args extends OptionDefinition>(adderDe
...
+        validateAddersOrExit<Args>(adderDetails, selectedAdderIds);
```
Comment (AdrianGonz97) [inline packages/core/adder/options.ts:141]: this too
```suggestion
        validateAddersOrExit(adderDetails, selectedAdderIds);
```

File: packages/core/adder/options.ts [hunk 4]
```diff
@@ -137,12 +137,27 @@ export function prepareAndParseCliOptions<Args extends OptionDefinition>(adderDe
...
+function validateAddersOrExit<Args extends OptionDefinition>(adderDetails: AdderDetails<Args>[], selectedAdderIds: string[]) {
+    const validAdderIds = adderDetails.map((x) => x.config.metadata.id);
+    const invalidAdders = selectedAdderIds.filter((x) => !validAdderIds.includes(x));
+
+    if (invalidAdders.length > 0) {
+        console.log("Invalid adder(s) selected:", invalidAdders.join(", "));
+        process.exit(0);
+    }
+
+    return selectedAdderIds;
```
Comment (AdrianGonz97) [inline packages/core/adder/options.ts:158]: it doesn't look like we're using the returned list anywhere, do you have plans to use it somewhere else?
```suggestion
```

**Review by AdrianGonz97 — CHANGES_REQUESTED** [review]
this is perfect! just needs a few changes

File: packages/core/adder/options.ts [hunk 5]
```diff
@@ -137,12 +137,27 @@ export function prepareAndParseCliOptions<Args extends OptionDefinition>(adderDe
...
 
     return options;
 }
 
+function validateAddersOrExit<Args extends OptionDefinition>(adderDetails: AdderDetails<Args>[], selectedAdderIds: string[]) {
+    const validAdderIds = adderDetails.map((x) => x.config.metadata.id);
+    const invalidAdders = selectedAdderIds.filter((x) => !validAdderIds.includes(x));
+
+    if (invalidAdders.length > 0) {
+        console.log("Invalid adder(s) selected:", invalidAdders.join(", "));
```
Comment (benmccann) [inline packages/core/adder/options.ts:154]:
```suggestion
        console.log(`Invalid adder${invalidAdders.length ? 's' : ''} selected:`, invalidAdders.join(", "));
```

File: packages/core/adder/options.ts (hunk 1 above)
Comment (benmccann) [inline packages/core/adder/options.ts:155]: should this be 1 to indicate an error?
```suggestion
        process.exit(1);
```

File: packages/core/adder/options.ts [hunk 6]
```diff
@@ -137,12 +137,27 @@ export function prepareAndParseCliOptions<Args extends OptionDefinition>(adderDe
...
+        const selectedAdderIds: string[] = program.args ?? [];
+        validateAddersOrExit<Args>(adderDetails, selectedAdderIds);
+
+        options.adder = selectedAdderIds;
     }
 
     return options;
 }
 
+function validateAddersOrExit<Args extends OptionDefinition>(adderDetails: AdderDetails<Args>[], selectedAdderIds: string[]) {
```
Comment (benmccann) [inline packages/core/adder/options.ts:149]: I think it could just be called `validateAdders`. I think "validate" often implies that it will throw an error if an issue is encountered
```suggestion
        const selectedAdderIds: string[] = program.args ?? [];
        validateAdders<Args>(adderDetails, selectedAdderIds);

        options.adder = selectedAdderIds;
    }

    return options;
}

function validateAdders<Args extends OptionDefinition>(adderDetails: AdderDetails<Args>[], selectedAdderIds: string[]) {
```

**Comment by manuel3108** [comment]
Merging, as storybook tests are failing because of something unrelated, see #475
