### PR TITLE
fix: alphabetize `dependencies` and `devDependencies`

### LINKED ISSUE #457: alphabetize dependencies/devDependencies
### Topic

core

### Version

2.3.6

### Expected behavior

should be alphabetized like with a newly created project

### Actual behavior

running the tailwind adder just added them to the end:
```
	"devDependencies": {
		"@fontsource/fira-mono": "^4.5.10",
		"@neoconfetti/svelte": "^1.0.0",
		"@sveltejs/adapter-auto": "^3.0.0",
		"@sveltejs/kit": "^2.0.0",
		"@sveltejs/vite-plugin-svelte": "^3.0.0",
		"svelte": "^4.2.7",
		"svelte-check": "^3.6.0",
		"tslib": "^2.4.1",
		"typescript": "^5.0.0",
		"vite": "^5.0.3",
		"tailwindcss": "^3.4.4",
		"postcss": "^8.4.38",
		"autoprefixer": "^10.4.19"
	},
```

### PR DESCRIPTION
**Pull request by AdrianGonz97**
closes #457

I'm not 100% sure that this is the right solution, but I'll point out my concerns below:

### CODE REVIEW

File: packages/ast-tooling/index.ts [hunk 1]
```diff
@@ -173,9 +173,9 @@ export function parseJson(content: string) {
...
 }
 
-// eslint-disable-next-line @typescript-eslint/no-explicit-any
-export function serializeJson(originalInput: string, data: any) {
+export function serializeJson(originalInput: string, data: unknown) {
     // some of the files we need to process contain comments. The default
     // node JSON.parse fails parsing those comments.
-    return fleece.patch(originalInput, data);
+    // return fleece.patch(originalInput, data);
+    return fleece.stringify(data);
```
Comment (AdrianGonz97) [inline packages/ast-tooling/index.ts:180]: From the docs for [`silver-fleece`](https://github.com/evertheylen/silver-fleece/blob/master/README.md), it looks like `patch` is used to preserve the formatting, but it's also interfering with our attempts of alphabetizing the dependencies. 

For instance, when we use the tailwind adder with the typography plugin included, all of the newly added deps are still be appended to the end of the dependency map:
img

File: packages/ast-tooling/index.ts [hunk 2]
```diff
@@ -173,9 +173,42 @@ export function parseJson(content: string) {
...
 }
 
-// eslint-disable-next-line @typescript-eslint/no-explicit-any
-export function serializeJson(originalInput: string, data: any) {
+export function serializeJson(originalInput: string, data: unknown) {
     // some of the files we need to process contain comments. The default
     // node JSON.parse fails parsing those comments.
-    return fleece.patch(originalInput, data);
+    const spaces = guessIndentString(originalInput);
+    return fleece.stringify(data, { spaces });
```
Comment (benmccann) [inline packages/ast-tooling/index.ts:180]: we should only pass `spaces` if the file is already using spaces and not if the file is using tabs

Comment (benmccann) [reply packages/ast-tooling/index.ts:180]: oh, nevermind. I see `guessIndentString` returns `undefined` for tabs, so it looks like we're okay there

**Review by benmccann — APPROVED** [review]

File: packages/ast-tooling/index.ts (hunk 2 above)
Comment (manuel3108) [inline packages/ast-tooling/index.ts:180]: This brings up a completely different topic that we had previously, but that does not apply at this point. 

Let's assume we have a `tsconfig.json` like this (created by `create-svelte`)
```json
{
	"extends": "./.svelte-kit/tsconfig.json",
	"compilerOptions": {
		"allowJs": true,
		"checkJs": true,
		"esModuleInterop": true,
		"forceConsistentCasingInFileNames": true,
		"resolveJsonModule": true,
		"skipLibCheck": true,
		"sourceMap": true,
		"strict": true,
		"moduleResolution": "bundler"
	}
	// Path aliases are handled by https://kit.svelte.dev/docs/configuration#alias
	// except $lib which is handled by https://kit.svelte.dev/docs/configuration#files
	//
	// If you want to overwrite includes/excludes, make sure to copy over the relevant includes/excludes
	// from the referenced tsconfig.json - TypeScript does not merge them in
}
```

With the approach we would now implement the comment would disappear, because the comments are not part of the JSON object. Currently we don't have that case active anymore, because we removed the routify? adder recently where this usecase came from. 

In order to get the best out of both worlds we should maybe introduce a new file type `json-comments` here 

https://github.com/svelte-add/svelte-add/blob/2f9a963fa826864c8207582b2f8fc3b83a893c44/packages/core/files/processors.ts#L56

and introduce some different handling, as I'm sure such a thing will happen in the future. On the other hand we could also leave it open for the future.

**Review by manuel3108 — CHANGES_REQUESTED** [review]

File: packages/ast-tooling/index.ts (hunk 2 above)
Comment (manuel3108) [reply packages/ast-tooling/index.ts:180]: We will just need to remember that in the future! But ok for now.

**Review by manuel3108 — APPROVED** [review]
